# Generated by Django 2.2.3 on 2019-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed_identifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogpicture',
            name='breed',
            field=models.CharField(default='Placeholder Breed', max_length=40),
        ),
    ]
